# See these links:
# - https://github.com/PHPirates/travis-ci-latex-pdf#tectonic-docker
# - https://github.com/japaric/trust
# - https://malramsay.com/post/compiling_latex_on_travis/

dist: bionic
sudo: required
language: generic
services: docker

env:
  global:
    # TODO Update this to match the proper filename of your pdf file
    # we can also specify datetime of the compiled document in by using before_deploy.sh
    - PDF_NAME=Rudo2204_thesis

# TODO: Update the following to install extra dependencies if needed
before_install:
  - set -e
  - sudo apt-get install texlive-extra-utils
  - sudo apt-get install python-pygments # If you use the minted package
# - sudo apt install ghostscript # If you use latex > dvips > ps2pdf
## If you use custom fonts:
# - mkdir $HOME/.fonts
# - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
# - fc-cache -f -v

install:
  - sh ci/texlive/texlive_install.sh

script:
# TODO: Change the following to compile the correct file(s)
  # Texliveonfly will download packages automatically
  # You can use latexmk to automatically handle bibtex and references (recommended)
  - sudo texliveonfly --compiler=latexmk --arguments='-pdf -shell-escape -synctex=1 -interaction=nonstopmode' main.tex

  # But you could use any other compiler (pdflatex, bibtex, pdflatex - have to do 2 times)
  # as well instead of latexmk.

after_script:
  - set +e
## Uncomment the following lines to see the packages installed in travis
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  # TODO update `api_key.secure`
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789 --pro`
  # - Paste the output down here
  api_key:
    secure: A9v3PIzQQ4U08OHFmDPQzNXbNHEb7YHyLXCvMF+dXFuNSvhUNlmQYykxqUf3dvikhJL2/bsZ14umm7ni7fQh0tGwJ4+lPpNzYAcweGgNXnWvjTpY6ovuRbr3gs4/srkyxp/GBDmSW5L8wFN3hKCB+Lm0YnIPB9IA2afP8a30+8VTXT9nv7pNqGny4ilN41ycr4DZi3sQoXdbruy7ClN7gsWW/GUiudBccHVIjmTapOFKLwZHODaUl/1/RDWQzh+i+17e1ivXuJPktDSrqmHPTZ15OjklnHKd6t179ry6VkGRg4R/R/YukVIqGzeaXGWAwdAQ5gE8cjGZghJLVi2jkDBJ85z8MvT+zLZLyliiuhLc/X8y7mkE1n0FKFtXXzFVt0l7V1LaEKbIbiV6XX3jsir4qgkqWjPHBZqO5mkGNFS16Dmt30/ZtEPAzXiINFXbWuWrpQ/LZ4NSto8IMrRTcoyDbAga/KYxJiNIeVuCe1E9dbytDM7K0GLtxJTul/WnnSeI6r//EFyC4bxYjyHhCXaag4q14KM+ak4rB0QgxsYzyGuh2MqyCoVj8YJLjLdKnL/SV7W7LPD40xlxvI6VCYTVi2ILHwL6vCxpukXYteX0c5IAIWkISDKu6nNBEgmCHXXPSqYSrgE5g7/QoCQHI8++nR8iKe0s7TWxZRydby8=
  # TODO: Change your file name here to package the right artifact
  fileglob: true
  file: ./*.pdf
  on:
    tags: true
  provider: releases
  skip_cleanup: true

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.texlive
  - chmod -R a+r /tmp/texlive

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never