name: Build
# TODO: Change the name of file to match writing guidelines
env:
  PDF_NAME: Thesis-Rudo2204

on: [push, pull_request]

jobs:
    build:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: main.tex # TODO: Change this to compile the correct file(s)
                  latexmk_shell_escape: true
            - uses: actions/upload-artifact@v2
              with:
                name: main.pdf
                path: main.pdf
            # Deploy
            - name: Rename Document
              if: startsWith(github.ref, 'refs/tags/v')
              shell: bash
              run: |
                cp main.pdf ${{ env.PDF_NAME }}.pdf
            - name: Upload PDF file
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                draft: true
                prerelease: false
                files: ${{ env.PDF_NAME }}.pdf
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
